# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: paul356's Blog
email: panhao356@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    In this blog you can find my thoughts, ideas and projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paul356.github.io" # the base hostname & protocol for your site
github_username: paul356

# Build settings
markdown: kramdown

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one